### ISSUE TITLE
Make Dotenv a soft dependency for development

### ISSUE THREAD

**Issue by jodosha** [hanami/hanami#516] opened 2016-02-15 17:54 UTC
## Actual

`dotenv` is a runtime dependency for `hanami`. We have included it, because hosting vendors use to provide configurations via env variables.

It happens that devs get confused about the main `.env` and they think it's for production purposes. This assumption is WRONG. Storing informations in that file is not a good security practice because that means to add them inside the Git repository.

Production env vars must be setup according to the hosting instructions. Heroku for instance, uses `heroku config:add`.

## Proposed

* Remove `dotenv` from runtime dependencies
* Generate new projects with `dotenv` in `:development`, `:test` groups in `Gemfile`
* Don't generate `.env` anymore
* Don't try to load `.env` anymore, but only `.env.development` or `.env.test`

Please note that `Hanami::Hanamirc` [uses `Dotenv` internally to parse `.hanamirc`](https://github.com/hanami/hanami/blob/master/lib/hanami/hanamirc.rb#L127). We must replace that code with a parser made by ourselves.

---

/cc @hanami/contributors WDYT?

**Comment by joneslee85** [comment] 2016-02-15 20:28
I :+1:. Production should _never_ store credentials in `.env` file.

**Comment by aderyabin** [comment] 2016-02-15 20:38
I propose more revolutionary way – to remove `dotenv` from any dependency totally. Developer can add `gem 'dotenv'` to generated `Gemfile` manually. From `hamani`side we can load environment variables or use default values.

**Comment by joneslee85** [comment] 2016-02-15 21:00
@aderyabin I think that would impose too much barrier for ease of use. I prefer to support `dotenv` as 1st-class citizen for dev env.

**Comment by simi** [comment] 2016-02-15 21:05
I think dotenv is not meant to be `hanami` (or another web framework) hard dependency. If someone decide to use it, it is so easy to do, that's not necessary to force every developer to download and bundle that dependency every time.

Custom parser can be used for `.hanamirc`. For example this one really naive fits all `.hanamirc`s in fixtures (or alternatively standrad CSV parser can be used with `=` as delimiter):

```ruby
class RcParser
  def self.parse(content)
    {}.tap do |hash|
      content.split("\n").each do |line|
        key, value = line.split('=')
        hash[key] = value
      end
    end
  end
end

require 'minitest/autorun'

class RcParserTest < Minitest::Test
  def test_parse
    content = "architecture=app
test=minitest
template=erb"

    options = {
      "architecture" => "app",
      "test" => "minitest",
      "template" => "erb"
    }

    assert_equal options, RcParser.parse(content)
  end
end
```

**Comment by JonathanSerafini** [comment] 2016-02-15 21:14
I'm just curious as to why you'd want to remove dotenv as a whole ... I for one have been finding it an extremely handy ( and standard ) way of configuration my application stacks. 

Specifically, I've been deploying Laravel apps with a /.env file ( single .env without environment namespace ) and Lotus apps with a /.env.production file ... both of these are templates that are generated by my configuration management system. 

Is the issue at hand that passwords should not be committed into Git ? Which is correct .. but the individual that would commit a password in .env would likely commit a password in config/passwords.rb or some such as well. Or perhaps the issue is something else entirely ?

**Comment by simi** [comment] 2016-02-15 21:16
@JonathanSerafini all you need to do is to add `dotenv` to Gemfile manually and create proper initializer or load `Dotenv.load` on proper place. The second option is create `dotenv-hanami` gem and do that work there. All you'll need to do afterwards will be adding one Gemfile entry.

**Comment by joneslee85** [comment] 2016-02-15 21:22
@simi i am having a crazy idea, why not using standard JSON or YAML format instead? It would be much easier to parse :)

**Comment by aderyabin** [comment] 2016-02-15 21:24
@simi Yep, definitely. 
There are 3 ways to use:

**Environment variable**
```
export HANAMI_PORT=2301
hanami server
```

**Option usage**
```
hanami server -p 2301
```

**Dotenv usage**
```
echo 'gem "dotenv"' >> Gemfile
bundle install
echo 'port=2302' >> .env
echo 'Dotenv.load' >> config/environment.rb
hanami server
```


Also, I agree with Mike Perham and his article "[Kill Your Dependencies](http://www.mikeperham.com/2016/02/09/kill-your-dependencies/)"

**Comment by aderyabin** [comment] 2016-02-15 21:25
@joneslee85  :+1: for YAML!

**Comment by joneslee85** [comment] 2016-02-15 21:25
@JonathanSerafini it is a very _bad_ practice to hardcode credential into files OR commit it that in Git history tree. We all know about the 12 factor rules. IMHO the framework should recommend best practices that would make the app secure from the beginning of dev to production stage.

**Comment by simi** [comment] 2016-02-15 21:26
@joneslee85 I was thinking about backward compatibility.

Actually this is valid YAML (and rubygems rc file is using that format):

```YAML
architecture: app
test: minitest
template: erb
```

**Comment by joneslee85** [comment] 2016-02-15 21:28
@simi with you on this too, if it is a legit YAML format already then it should be quite straight-forward to implement the parser.

**Comment by simi** [comment] 2016-02-15 21:30
It is valid YAML format, but it is not compatible with current format. I'm not sure how to handle this. Will be deprecation cycle needed for that? I can provide PR for format change with parser and all that stuff.

current format:

```
architecture=app
test=minitest
template=erb
```

proposed format:

```yaml
architecture: app
test: minitest
template: erb
```

**Comment by aderyabin** [comment] 2016-02-15 21:30
@simi, @joneslee85  generate in YAML starting the next release. As for backward compatibility. There are few ways:
– convert to yaml automatically
– raise error and ask to convert
– support current format next few releases.

**Comment by JonathanSerafini** [comment] 2016-02-15 21:38
@joneslee85 I agree with you that hard coding credentials is a horrible idea ... 

What I was getting at is that dotenv does not force you or recommend that you hard code anything, it simply provides you with a standard method in which to configure your application. Removing this dependency will have no impact on whether anyone decides to hard code their secrets. 

Granted other formats would provide more flexibility, which is great, but they won't prevent poor developer security practices. 

Anyhow, just thought I'd add my 2cents given that security seemed to be the primary driving factor for this change initially.

**Comment by aderyabin** [comment] 2016-02-15 21:51
One more way
```
hanami new bookshelf --dotenv
```
It generates dotenv files and add `Dotenv.load` execution

**Comment by jodosha** [comment] 2016-02-16 09:25
Wow, I leave you for a day and you run so fast!

Let me clarify a few points:

  * We're doing this to reduce (aka kill) the dependencies as much as possible. We always did it, and it's valuable.

  * Dotenv is gonna to stay as soft dependency, by default for `:development` and `:test` groups. It will be **installed by default** when a developer will execute `bundle install`.

  * Developers can opt-out. Dotenv "just works" and we want to offer a smooth default experience.

  * Asking to opt-in for Dotenv and generate the related files it's the opposite of a smooth experience, and not user friendly. :-1: 

  * We don't wanna change the `.hanamirc` format

  * Because Dotenv will no longer be a hard dependency, it won't be installed anymore in production

  * No `--dotenv` arguments for `hanami new`

  * YAML :-1: 

  * Developers like @JonathanSerafini which still need Dotenv in production, can move the gem from `:development`, `:test` groups to the general one. See the example below.

---

### Use Dotenv in Production

The default `Gemfile` should be

```ruby
# ...

group :development, :test do
  gem 'dotenv'
end
```

If you need to use it in production:


```ruby
# ...

gem 'dotenv'
```

That's it.

Using it in production is NOT a bad practice per sé. If you do NOT store `.env.production` in Git, but let a system like Chef to generate it in production env and store it there it's more secure.

I won't do like that, but it's better to store it in Git or have `config/initializers/secrets.rb`, which is a bad idea.

**Comment by aderyabin** [comment] 2016-02-16 19:48
What do you think about adding `.env.production` to `.gitignore` ?

**Comment by hlegius** [comment] 2016-02-17 00:56
My 2 cents:

> Using it in production is NOT a bad practice per sé. If you do NOT store .env.production in Git, but let a system like Chef to generate it in production env and store it there it's more secure.

I know some Ops that doesn't like that 12 factor 'rules' and uses `Dotenv` in production as well exactly how you've described using Ansible without storing any production keys into git.

Also, `Dotenv` is pretty simple/handy to use in dev/test modes. So, as soft dependency :+1:

**Closed** 2016-02-18 08:46 UTC
Labels: discussion, enhancement
