### ISSUE TITLE
Setting the format of actions at App has no effect

### ISSUE THREAD

**Issue by wuarmin** [hanami/hanami#1245] opened 2022-11-08 09:30 UTC
Hey,
if I set the action format as explained in the latest [blog post](https://hanamirb.org/blog/2022/10/24/announcing-hanami-200beta4/#simplified-body-parser-config), but the response format of my slice-action keeps to be 

```ruby
module Services
  class App < Hanami::App
    config.actions.format json: "application/json"
  end
end
```

```txt
Content-Type: text/html; charset=utf-8
```
**Workaround:**
```ruby
module MySlice
  module Actions
    module Notifications
      class Upload < MySlice::Action
        def handle(req, res)
          res.format = format(:json)
          ...
        end
      end
    end
  end
end
```
**Another question:** What's the best way to set a format/body_parser for a slice?

Thanks

**Comment by timriley** [comment] 2022-11-08 09:35
@wuarmin I think you want this:

```ruby
config.actions.format json: "application/json"
config.actions.default_response_format = :json
```

`.format` just registers the content type for that format name. The `default_response_format` config will effectively run the code from your workaround automatically for every action.

Could you please give this a go and confirm for me?

**Comment by wuarmin** [comment] 2022-11-08 10:11
@timriley Thanks, understood, but unfortunately
```ruby
config.actions.default_response_format = :json
```
has also not effect.

Do you have some input for:
> Another question: What's the best way to set a format/body_parser for a slice?
Thanks

**Comment by timriley** [comment] 2022-11-08 12:10
> What's the best way to set a format/body_parser for a slice?

Try this:

```ruby
module MyApp
  class App < Hanami::App
    config.actions.format json: "application/json"
    config.actions.default_request_format = :json
    config.actions.default_response_format = :json
    config.middleware.use :body_parser, :json
  end
end
```

Routes:

```ruby
module MyApp
  class Routes < Hanami::Routes
    slice :main, at: "/" do
      post "/", to: "home.show"
    end
  end
end
```

Action:

```ruby
module Main
  module Actions
    module Home
      class Show < Main::Action
        def handle(request, response)
          response.body = request.params[:foo].inspect
        end
      end
    end
  end
end
```

curl:

```
curl -X POST http://localhost:2300/ -H 'Content-Type: application/json' -d '{"foo":"bar"}'
"bar"⏎
```

Looks like it all works as it should.

**Comment by timriley** [comment] 2022-11-08 12:12
I'm going to close this for now, but feel free to reply if you have any issues.

**Closed by timriley** 2022-11-08 12:12 UTC

**Comment by wuarmin** [comment] 2022-11-09 10:20
@timriley thank you for the help. Yes, now it works. I didn't check it with curl. I just checked the resp-headers in my browser and the Content-Type is `text/html` (with curl outputs `application/json`)
![image](https://user-images.githubusercontent.com/9987680/200803682-1561f9c2-de8b-40d0-b3fb-b6dcb1843da4.png)
but if I set the format at action-level `res.format = format(:json)` my browser shows the right Content-Type
![image](https://user-images.githubusercontent.com/9987680/200804056-b50ef029-a7c9-4db2-adc3-e6bfb5a74749.png)

Regarding the question:
> What's the best way to set a format/body_parser for a slice?
Thank you, but I meant how to set the default request and response format for a specific slice? I.e slice **main** should respond with `text/html` and slice **api** with `application/json`

Thanks!

**Comment by timriley** [comment] 2022-11-10 23:34
@wuarmin Ah, the reason you're getting `Content-Type: text/html` in the response from your browser's request is that your browser is setting an `Accept` header that looks like this:

```
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
```

I can confirm I've replicated this locally.

Here's why it happens: when Hanami::Action sets up its response object, it prepares a default `Content-Type` response header based on this `Accept` header, if it is present. See https://github.com/hanami/controller/blob/f66d91beef8023a1dd2d41c51aa3168f2060d2a4/lib/hanami/action/mime.rb#L77-L95 for the implementation. What this shows is that the default_response_format will only be used if there is no `Accept` header.

Luckily we have one more trick up our sleeve, which is to put `accept :json` in the body of an action class. When I do this with my test app, and then make a request to it, I get the right `Content-Type` in the response:

```
curl -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" --head http://localhost:2300/

HTTP/1.1 200 OK
<snip>
Content-Type: application/json; charset=utf-8
Content-Length: 13
```

`accept` in an action class is just a shortcut for setting `config.accepted_formats`, so you could also this this in your app along with the others:

```ruby
module MyApp
  class App < Hanami::App
    config.actions.format json: "application/json"
    config.actions.accepted_formats = [:json]
    config.actions.default_request_format = :json
    config.actions.default_response_format = :json
    config.middleware.use :body_parser, :json
  end
end
```

I realise this is a whole lot of `:json` in one place; it's not the streamlined experience we would like, but it's what works right now. I'll definitely think on how we could improve this.

Please give this a go and let me know how it works for you!

--- 

> > What's the best way to set a format/body_parser for a slice?
>
> Thank you, but I meant how to set the default request and response format for a specific slice? I.e slice main should respond with text/html and slice api with application/json

To set a body parser middleware for a single slice only, you'll need to put it inside that slice's scope in your routes:

```ruby
# config/routes.rb

module MyApp
  class Routes < Hanami::Routes
    slice :my_api, at: "/api" do
      use :body_parser, :json
    end
  end
end
```

I haven't had a chance to test this specifically, so please let me know how you go.

Then to set config for actions within a slice, you have two options:

First, you could create a slice class at `config/slices/[slice_name].rb` and do this:

```ruby
module MyAPI
  class Slice < Hanami::Slice
    config.actions.default_response_format = :json # or any other config
  end
end
```

Or if you have a base action class within your slice (from which all other actions inherit), you could choose to do it there instead:

```ruby
# slices/my_api/action.rb

module MyAPI
  class Action < MyApp::Action
    config.default_response_format = :json # or any other config
  end
end
```

Let me know how you go :)

**Comment by wuarmin** [comment] 2023-01-10 15:39
Hey @timriley,

I stumbled across this behavior again. Following format settings have no effect for a requesting browser with following `Accept`-Header:
```txt
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
```
```ruby
# config/app.rb

module Bookshelf
  class App < Hanami::App
    config.actions.format :json
  end
end

```
```ruby
# app/action.rb

module Bookshelf
  class Action < Hanami::Action
    config.format :json
  end
end
```

```ruby
# app/actions/books/index.rb

module Bookshelf
  module Actions
    module Books
      class Index < Bookshelf::Action
        format :json # or `config.format :json`

        def handle(request, response)
          # ...
        end
      end
    end
  end
end
```

The only way to enforce the correct response header for browser requests is this:
```ruby
# app/actions/books/index.rb

module Bookshelf
  module Actions
    module Books
      class Index < Bookshelf::Action

        def handle(res, req)
          res.format = format("application/json")
        end
      end
    end
  end
end
```
Back then you showed me a workaround using `accepted_formats` that doesn't work with current hanami version. Do we have to change the implementation of https://github.com/hanami/controller/blob/f66d91beef8023a1dd2d41c51aa3168f2060d2a4/lib/hanami/action/mime.rb#L77-L95?

Thanks!
