### ISSUE TITLE
Performance issue with rendering a partial view

### ISSUE THREAD

**Issue by smt116** [hanami/hanami#185] opened 2015-03-18 23:00 UTC
Hi there ;)

I have a [sample application](https://github.com/smt116/lotus-sample-application). It seems that using `render partial: "foo"` (or `render template: "foo"` etc) results in really poor performance. Take a look at this [change](https://github.com/smt116/lotus-sample-application/commit/707ca41358cb952bc1d93e0eb72e6118744d3ffe). It reduces performance 10 times!

Here is output of [wrk](https://github.com/wg/wrk) without rendering a partial inside a layout:

```bash
2.2.1 ~/repos/lotus-application master
 $ wrk --connections 4 --duration 5 --threads 4 http://localhost:2500
Running 5s test @ http://localhost:2500
  4 threads and 4 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.14ms    2.56ms  27.95ms   92.90%
    Req/Sec   645.90    231.82     1.33k    63.98%
  12367 requests in 5.00s, 8.41MB read
Requests/sec:   2473.83
Transfer/sec:      1.68MB
```

and here is after change:

```bash
2.2.1 ~/repos/lotus-application partial
 $ wrk --connections 4 --duration 5 --threads 4 http://localhost:2500
Running 5s test @ http://localhost:2500
  4 threads and 4 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    20.86ms   15.98ms  92.89ms   86.53%
    Req/Sec    63.61     26.03   128.00     65.07%
  1280 requests in 5.01s, 0.87MB read
Requests/sec:    255.71
Transfer/sec:    178.05KB
```

As you can see 2.9k req/sec vs 0.29k req/sec. I am using slim in this case, but it seems to be a general issue. I checked with haml and it remains the same.

## How to reproduce

```bash
 # clone repo
 $ git clone git@github.com:smt116/lotus-sample-application.git

 # install gems
 $ cd lotus-sample-application && bundle install

 # create config for postgresql database
 $ cp config/.env.example config/.env && vim config/.env

 # optional: setup database
 $ rake db:create && rake db:migrate && rake db:seed
```

Perform a benchmark on `master` and `partial` branchs:

```bash
 # run server
 $ RACK_ENV=production puma --threads 4:4 --port 2500 --preload --quiet
```

```bash
 # perform stress test using https://github.com/wg/wrk
 $ wrk --connections 4 --duration 5 --threads 4 http://localhost:2500
```

---

I talked with @jodosha and with @joneslee85 and I said that I will post it on the forum, but I think that it is more like an issue to fix than a post to discuss. I can move it there if you want ;).

I can investigate it further if you want.

**Comment by jodosha** [comment] 2015-03-19 08:34
@smt116 Thanks for your extensive explanation about this issue. I'm **really** glad that you found this issue. Because you were able to isolate the slow component, have you tried to profile it?

That `#render` method is [defined](https://github.com/lotus/view/blob/master/lib/lotus/view/rendering/layout_scope.rb#L83) in `Lotus::View::Rendering::LayoutScope`. My suspect is that **in this case** the partial or the template file (eg. `_footer.html.erb`) are loaded from the file system **for each request**.

This has a huge perf impact, that's why `Lotus::View.load!` preloads all the templates in memory before to start the app. This should be the reason of the difference between the two type of renderings.

In order to fix this, `Lotus::View.load!` should be able to preload all those templates/partials and to access to another registry at the runtime. This would reproduce exactly what the "normal" view/template rendering cycle is.

Would you like to take care of this? This should go in `lotus-view` :smile: Thank you.

**Comment by smt116** [comment] 2015-03-19 08:39
Hi @jodosha,

I will take a look at this and try to solve ;)

**Comment by jeremyf** [comment] 2015-03-23 01:30
@smt116 friendly ping

**Comment by smt116** [comment] 2015-03-23 07:32
Hi @jeremyf,

I didn't have enough time for doing it yet. I have started to read `lotus-view` source code in the weekend. Feel free to take this from me if you like (just let me know)

**Comment by jeremyf** [comment] 2015-03-24 23:10
@smt116 just checking if you had a chance.

**Comment by smt116** [comment] 2015-03-30 21:04
Do you think that all partials / templates should be preloaded on the server start or just loaded on the first request? I am thinking about the method for finding all associated partials and loading them on the server start, but not sure how to achieve it without scaning directory for the `_*` files or greping templates.

**Comment by jodosha** [comment] 2015-04-07 09:17
@smt116 They should be preloaded at the startup time. Lazy code loading isn't thread safe.

**Comment by smt116** [comment] 2015-04-09 11:46
Any idea on how to load necessary partials/templates for given view?

**Comment by agenteo** [comment] 2015-06-18 06:32
Hi guys, I took a peak at this today to help moving forward, first of all should the issue be moved or at least tracked in [lotus-view](https://github.com/lotus/view)?

I located the commit introducing partial rendering at https://github.com/lotus/view/commit/ba5acdc30673bfeeecda2c61217884bdd7d5f20c

I was looking at what Luca said about the templates being pre-loaded from `Lotus::View.load!`: https://github.com/lotus/view/blob/master/lib/lotus/view.rb#L289 which calls Configuration#load! https://github.com/lotus/view/blob/master/lib/lotus/view/configuration.rb#L362

what I didn't understand is at what point is the `views` set populated? Is the private `add_view` (https://github.com/lotus/view/blob/master/lib/lotus/view/configuration.rb#L330) used at all?

Cheers

**Comment by jodosha** [comment] 2015-06-18 12:30
@agenteo Hi.

> I understand you leverage tilt to render but I couldn't find where the preload is.

https://github.com/lotus/view/blob/master/lib/lotus/view/rendering/registry.rb

**Comment by agenteo** [comment] 2015-06-18 23:34
Thanks for pointing to that, when/where are the views handed over from the https://github.com/lotus/view/blob/master/lib/lotus/view/configuration.rb#L330 `Set` to the Registry?

**Comment by pascalbetz** [comment] 2015-07-30 18:33
I've looked into this a bit. My understanding:

* Template caching can be done because it's predefined what template a view renders: either inferred through the name or trough the ```.template``` method defined in dsl.rb#206
* Templates are cached per view. If two views are rendering the same template it is loaded twice

To me it looks like Template instances are created at least twice on startup. This is due to ```LayoutRegistry#templates``` being called twice (seems like a bug to me?):

* ```LayoutRegistry#prepare!```
* ```Registry#prepare!``` (indirectly via _prepare_views!_ -> _template_for_)

Also:

Partials are harder to cache since they are only identified upon rendering a tilt template (which can be a layout, template, partial) trough the call to ```render partial: 'foo'```.

So it looks like partials can only be cached at runtime and not during startup, at least not the way templates are currently cached and preloaded.

Idea:

Create a "global" Template (layout/partial/template) registry which preloads template files (if it is a FileSystemRegistry, for rails i once had to store templates in a DB) independently from the views. It provides methods to fetch a template by its name (a path) and format.
Preloading the registry could be done at startup by scanning the FS. With, depending on the environment, caching or reloading (reload if mtime of file changed?)

This would allow to unify the mechanism in which templates are preloaded for layouts/templates/partials. Also the same Template would only be loaded once, even when multiple views use it.

Not completely thought trough... feedback?

**Comment by noahc** [comment] 2015-10-20 13:25
Is this still an issue? I'm happy to take a look at it and see if I can make some headway.

**Comment by pascalbetz** [comment] 2015-10-20 13:41
I think it is still an issue. Perhaps @jodosha can give some feedback on the findings.

**Comment by jodosha** [comment] 2015-10-20 15:06
@noahc Please proceed, I haven't investigated since my last reply above. :+1:

**Comment by stevehook** [comment] 2016-01-01 22:08
If this is still an issue I'd be happy to try and work out a fix over the next few days.

Seems to me it would be possible to load partial templates into the framework configuration object much like layouts and regular view templates, but by scanning the file system as suggested above.

I've got something rough working, is it worth tidying it up and raising a PR?

**Comment by joneslee85** [comment] 2016-01-02 01:14
@stevehook sure, definitely, please send the PR over

**Comment by pascalbetz** [comment] 2016-01-02 08:56
@stevehook would be interested in seeing it. let me know when you are done.

**Comment by jodosha** [comment] 2016-01-02 14:21
@pascalbetz If you have time and/or interest, please take care of it. :+1:

**Comment by pascalbetz** [comment] 2016-01-02 19:42
@jodosha: @stevehook has already a PR in the works. i'm happy to support him if he is working on it. otherwise: let me know and i can take over.

**Comment by jodosha** [comment] 2016-01-02 20:58
@stevehook Ping. :smile: Where is your PR? /cc @pascalbetz

**Comment by stevehook** [comment] 2016-01-02 22:20
@pascalbetz & @jodosha I've raised a PR now, including a couple of questions. Hopefully I haven't gone too far off track!

**Comment by jodosha** [comment] 2016-01-03 12:29
@stevehook Thank you very much! :+1: I left comments over there :smile:

**Comment by jodosha** [comment] 2016-01-29 14:56
Closed by https://github.com/hanami/view/pull/86

**Closed by jodosha** 2016-01-29 14:56 UTC
