### ISSUE TITLE
Inconsistent naming in generating app / models

### ISSUE THREAD

**Issue by flarik** [hanami/hanami#585] opened 2016-05-27 15:14 UTC
When generated an app with an dash in in. the "hanami new" command will generate files/dirs with an underscore in it.
When generating a model in the sam app with "hanami generate model" it will generate files/dirs with a dash in it (like the original).

This is inconsistent behaviour and IMHO should be like the model: do not convert the dash to an underscore.

Example:

When creating the app a dash is converted to an underscore in file naming: love-dashes becomes love_dashes

```
$ hanami new love-dashes
$ cd love-dashes
$ tree -L 3 lib spec
lib
├── config
│   └── mapping.rb
├── love_dashes
│   ├── entities
│   ├── mailers
│   │   └── templates
│   └── repositories
└── love_dashes.rb
spec
├── features_helper.rb
├── love_dashes
│   ├── entities
│   ├── mailers
│   └── repositories
├── spec_helper.rb
├── support
└── web
    ├── controllers
    ├── features
    └── views
```

When generating a model in the same app, it uses a dash instead of the underscore for naming, so you end up with an love-dashes and love_dashes directory inside lib/ and spec/.

```
$ hanami generate model books
      create  lib/love-dashes/entities/books.rb
      create  lib/love-dashes/repositories/books_repository.rb
      create  spec/love-dashes/entities/books_spec.rb
      create  spec/love-dashes/repositories/books_repository_spec.rb
$ tree -L 3 lib spec
lib
├── config
│   └── mapping.rb
├── love-dashes
│   ├── entities
│   │   └── books.rb
│   └── repositories
│       └── books_repository.rb
├── love_dashes
│   ├── entities
│   ├── mailers
│   │   └── templates
│   └── repositories
└── love_dashes.rb
spec
├── features_helper.rb
├── love-dashes
│   ├── entities
│   │   └── books_spec.rb
│   └── repositories
│       └── books_repository_spec.rb
├── love_dashes
│   ├── entities
│   ├── mailers
│   └── repositories
├── spec_helper.rb
├── support
└── web
    ├── controllers
    ├── features
    └── views
```

This seems to be related to #499

**Comment by kolybasov** [comment] 2016-05-27 19:54
@flarik had this problem too. Tried to submit PR, but discovered that it was already fixed at v0.8  :) Now `hanami generate model books` will create files in underscored folder `lib/love_dashes/entities/books.rb …`

**Comment by jodosha** [comment] 2016-05-28 09:45
@flarik Thanks for reporting, can you please confirm that master fixes the problem for you? Please check these instructions: https://github.com/hanami/hanami#how-to-use-hanami-head

**Comment by flarik** [comment] 2016-05-30 06:37
@jodosha Works with master.

**Comment by jodosha** [comment] 2016-05-31 15:41
@flarik Hey thanks for your reply!

---

Closing this as duplicate of #490 - Ref #491 #529

**Closed by jodosha** 2016-05-31 15:41 UTC
Labels: duplicate
