### ISSUE TITLE
hanami server --debug throws an exception

### ISSUE THREAD

**Issue by Defman21** [hanami/hanami#629] opened 2016-08-05 08:03 UTC
If I'm trying to run `hanami server --debug`, it always throws an exception.

I did `hanami assets precompile` so `public/assets.json` will be generated and that didn't help.

```
nil
#<Rack::ContentLength:0x00564638d10dd8
 @app=
  #<Rack::CommonLogger:0x00564638d10e50
   @app=
    #<Rack::ShowExceptions:0x00564638d41c30
     @app=
      #<Rack::Lint:0x00564638d41ca8
       @app=
        #<Hanami::Assets::Static:0x00564638d52058
         @app=
          #<Shotgun::Loader:0x00564635e75398
           @config=
            #<Proc:0x00564635e752f8@/home/defman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/shotgun-0.9.1/lib/shotgun/loader.rb:14>,
           @rackup_file="/home/defman/server/<private>/config.ru">,
         @file_server=
          #<Rack::File:0x00564638d41ed8
           @default_mime="text/plain",
           @headers={},
           @root=#<Pathname:/home/defman/server/<private>/public>>,
         @header_rules=[],
         @index=nil,
         @sources=
          {"/assets/"=>
            #<Hanami::Assets::Configuration:0x00564639258200
             @base_url="http://localhost:2300",
             @cdn=false,
             @compile=true,
             @destination_directory=nil,
             @digest=false,
             @digest_manifest=Exception `Hanami::Assets::MissingDigestManifestError' at /home/defman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hanami-assets-0.3.0/lib/hanami/assets/config/manifest.rb:65 - Can't read manifest: /home/defman/server/<private>/public/assets.json
Exception `Hanami::Assets::MissingDigestManifestError' at /home/defman/.rbenv/versions/2.3.0/bin/hanami:23 - Can't read manifest: /home/defman/server/<private>/public/assets.json
/home/defman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hanami-assets-0.3.0/lib/hanami/assets/config/manifest.rb:65:in `method_missing': Can't read manifest: /home/defman/server/<private>/public/assets.json (Hanami::Assets::MissingDigestManifestError)
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:180:in `pp'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:266:in `block (3 levels) in pp_object'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:253:in `block (2 levels) in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:280:in `nest'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:252:in `block in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:265:in `group_sub'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:251:in `group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:264:in `block (2 levels) in pp_object'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:252:in `block in seplist'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:246:in `each'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:246:in `seplist'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:259:in `block in pp_object'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:253:in `block (2 levels) in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:280:in `nest'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:252:in `block in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:265:in `group_sub'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:251:in `group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:207:in `object_address_group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:258:in `pp_object'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:320:in `pretty_print'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:189:in `block in pp'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:253:in `block (2 levels) in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:280:in `nest'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:252:in `block in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:265:in `group_sub'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:251:in `group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:189:in `pp'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:281:in `block (4 levels) in pp_hash'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:253:in `block (2 levels) in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:280:in `nest'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:252:in `block in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:265:in `group_sub'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:251:in `group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:279:in `block (3 levels) in pp_hash'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:253:in `block (2 levels) in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:280:in `nest'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:252:in `block in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:265:in `group_sub'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:251:in `group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:276:in `block (2 levels) in pp_hash'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:252:in `block in seplist'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:246:in `each_pair'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:246:in `seplist'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:275:in `block in pp_hash'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:253:in `block (2 levels) in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:280:in `nest'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:252:in `block in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:265:in `group_sub'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:251:in `group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:274:in `pp_hash'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:373:in `pretty_print'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:189:in `block in pp'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:253:in `block (2 levels) in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:280:in `nest'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:252:in `block in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:265:in `group_sub'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:251:in `group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:189:in `pp'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:266:in `block (3 levels) in pp_object'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:253:in `block (2 levels) in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:280:in `nest'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:252:in `block in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:265:in `group_sub'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:251:in `group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:264:in `block (2 levels) in pp_object'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:252:in `block in seplist'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:246:in `each'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:246:in `seplist'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:259:in `block in pp_object'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:253:in `block (2 levels) in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:280:in `nest'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:252:in `block in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:265:in `group_sub'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:251:in `group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:207:in `object_address_group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:258:in `pp_object'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:320:in `pretty_print'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:189:in `block in pp'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:253:in `block (2 levels) in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:280:in `nest'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:252:in `block in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:265:in `group_sub'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:251:in `group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:189:in `pp'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:266:in `block (3 levels) in pp_object'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:253:in `block (2 levels) in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:280:in `nest'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:252:in `block in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:265:in `group_sub'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:251:in `group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:264:in `block (2 levels) in pp_object'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:252:in `block in seplist'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:246:in `each'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:246:in `seplist'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:259:in `block in pp_object'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:253:in `block (2 levels) in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:280:in `nest'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:252:in `block in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:265:in `group_sub'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:251:in `group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:207:in `object_address_group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:258:in `pp_object'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:320:in `pretty_print'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:189:in `block in pp'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:253:in `block (2 levels) in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:280:in `nest'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:252:in `block in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:265:in `group_sub'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:251:in `group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:189:in `pp'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:266:in `block (3 levels) in pp_object'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:253:in `block (2 levels) in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:280:in `nest'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:252:in `block in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:265:in `group_sub'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:251:in `group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:264:in `block (2 levels) in pp_object'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:252:in `block in seplist'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:246:in `each'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:246:in `seplist'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:259:in `block in pp_object'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:253:in `block (2 levels) in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:280:in `nest'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:252:in `block in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:265:in `group_sub'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:251:in `group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:207:in `object_address_group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:258:in `pp_object'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:320:in `pretty_print'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:189:in `block in pp'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:253:in `block (2 levels) in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:280:in `nest'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:252:in `block in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:265:in `group_sub'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:251:in `group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:189:in `pp'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:266:in `block (3 levels) in pp_object'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:253:in `block (2 levels) in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:280:in `nest'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:252:in `block in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:265:in `group_sub'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:251:in `group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:264:in `block (2 levels) in pp_object'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:252:in `block in seplist'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:246:in `each'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:246:in `seplist'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:259:in `block in pp_object'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:253:in `block (2 levels) in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:280:in `nest'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:252:in `block in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:265:in `group_sub'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:251:in `group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:207:in `object_address_group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:258:in `pp_object'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:320:in `pretty_print'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:189:in `block in pp'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:253:in `block (2 levels) in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:280:in `nest'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:252:in `block in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:265:in `group_sub'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:251:in `group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:189:in `pp'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:266:in `block (3 levels) in pp_object'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:253:in `block (2 levels) in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:280:in `nest'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:252:in `block in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:265:in `group_sub'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:251:in `group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:264:in `block (2 levels) in pp_object'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:252:in `block in seplist'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:246:in `each'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:246:in `seplist'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:259:in `block in pp_object'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:253:in `block (2 levels) in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:280:in `nest'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:252:in `block in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:265:in `group_sub'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:251:in `group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:207:in `object_address_group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:258:in `pp_object'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:320:in `pretty_print'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:189:in `block in pp'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:253:in `block (2 levels) in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:280:in `nest'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:252:in `block in group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:265:in `group_sub'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/prettyprint.rb:251:in `group'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:189:in `pp'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:101:in `block in pp'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:148:in `guard_inspect_key'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:101:in `pp'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:23:in `block in pp'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:22:in `each'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pp.rb:22:in `pp'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/server.rb:264:in `start'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hanami-0.8.0/lib/hanami/commands/server.rb:33:in `start'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hanami-0.8.0/lib/hanami/cli.rb:46:in `server'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/defman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hanami-0.8.0/bin/hanami:5:in `<top (required)>'
	from /home/defman/.rbenv/versions/2.3.0/bin/hanami:23:in `load'
	from /home/defman/.rbenv/versions/2.3.0/bin/hanami:23:in `<main>'
```

**Comment by cllns** [comment] 2016-08-05 15:56
What if you do `touch public/assets.json` and precompile then try again?

**Comment by Defman21** [comment] 2016-08-05 16:43
Same error.

**Comment by cllns** [comment] 2016-08-05 17:25
And `chmod 777 public/assets.json` ? then precompile and try again?

**Comment by Defman21** [comment] 2016-08-05 17:36
Still same :(

**Comment by cllns** [comment] 2016-08-05 18:05
So when you run just `hanami server`, everything runs as intended? And it's just `--debug` that causes problems? I'm thinking it's an issue with `inspect`-ing the `NullDigestAssetManifest`: https://github.com/hanami/assets/blob/010d2b0aa980662a9cd884972aeab74de7a3ea8e/lib/hanami/assets/config/manifest.rb#L66

**Comment by Defman21** [comment] 2016-08-05 18:31
>So when you run just hanami server, everything runs as intended? 

Yes.

>And it's just --debug that causes problems?

Yes.

**Comment by jodosha** [comment] 2016-08-10 15:49
@Defman21 I'm sorry about this problem. The fix was merged. Expect a patch release later this week.

**Closed** 2016-08-10 15:49 UTC
Labels: bug
