### ISSUE TITLE
Test suite failure when using `flash` in layout

### ISSUE THREAD

**Issue by Pistos** [hanami/hanami#903] opened 2018-02-24 15:56 UTC
### Steps to Reproduce

    hanami new flash-bug --test=rspec
    cd flash_bug
    bundle install
    bundle exec rake spec  # observe green test suite
    ${EDITOR} apps/web/templates/application.html.erb
    # Add flash in the <body>, such as: <p><%= flash[:foo] %></p>
    bundle exec rake spec  # test suite fails

### Actual Behaviour

```
  1) Web::Views::ApplicationLayout contains application name 
     Failure/Error: let(:rendered) { layout.render }
                                                 
     NameError:         
       undefined local variable or method `flash' for #<Hanami::View::Rendering::LayoutScope:0x0000561c21d158b0>
     # /home/pistos/.rvm/gems/ruby-2.5.0@hanami-test/gems/hanami-view-1.1.0/lib/hanami/view/rendering/layout_scope.rb:236:in `method_missing'
```

### Expected Behaviour

* A fully passing test suite

### Notes

* Possibly related: https://github.com/hanami/hanami/issues/859
* When you run the app with `bundle exec hanami server`, and visit the site, *there is no error*.
* If you actually set `flash[:foo]` to something, it displays just fine in the app (in browser).  i.e. this problem is strictly with the test suite.

**Comment by davydovanton** [comment] 2018-02-25 21:40
I'll try to reproduce it, thanks for the report 👍

**Comment by jodosha** [comment] 2018-03-12 10:59
@Pistos Which version of Hanami are you using?

**Comment by Pistos** [comment] 2018-03-12 15:23
> Which version of Hanami are you using?

The `Gemfile.lock` in the dir says 1.1.0.

**Comment by jodosha** [comment] 2018-03-22 18:22
@Pistos 

> When you run the app with bundle exec hanami server, and visit the site, there is no error.

To see the error, you should hit an action that uses `apps/web/templates/application.html.erb`. If you don't have actions in your project, you're **not** rendering that application template, so `flash` isn't evaluated and everything looks fine.

Try to do:

```shell
$ bundle exec hanami generate action web home#index --url=/
$ bundle exec hanami server
```

Then visit `http://localhost:2300`, and you'll see the problem.

![screen shot 2018-03-22 at 19 16 39](https://user-images.githubusercontent.com/5089/37790050-c6df1e78-2e05-11e8-9073-8b7d1282939a.png)

The test suite should not pass because sessions aren't enabled. This is the expected behavior.

---

Now, I agree that the error message should be improved, that's why we just merged https://github.com/hanami/hanami/pull/915. 😄

**Closed by jodosha** 2018-03-22 18:22 UTC
Labels: bug

**Comment by Pistos** [comment] 2018-03-22 19:41
Great, thank you for the explanation and the fix!

**Comment by DannySantos** [comment] 2019-12-24 11:46
I'm experiencing this same issue despite the fact I have enabled sessions and have an action that uses `application.html.erb`

When I visit `http://localhost:2300/users/new` there is no error message, but when I run the application_layout view spec I get the exact same error as @Pistos.

**Comment by cllns** [comment] 2019-12-24 20:50
@DannySantos Can you create an example Hanami project that reproduces the bug, then open a new Issue with a link to that repo on GitHub, and mention this issue? Thanks :)
