### ISSUE TITLE
v1.3.3 causes an "uninitialized constant Hanami::View::Rendering::Scope::String"

### ISSUE THREAD

**Issue by inouire** [hanami/hanami#1015] opened 2019-09-24 19:33 UTC
Since my upgrade from 1.3.2 to 1.3.3, my app doesn't start, here is the stack trace

```
Boot Error

Something went wrong while loading .../project/config.ru
NameError: uninitialized constant Hanami::View::Rendering::Scope::String Did you mean? String StringIO STDIN

.../project/apps/web/templates/account/login.html.erb:1:in `__tilt_47450820803780'
.../.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/tilt-2.0.10/lib/tilt/template.rb:170:in `call'
.../.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/tilt-2.0.10/lib/tilt/template.rb:170:in `evaluate'
.../.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/tilt-2.0.10/lib/tilt/template.rb:109:in `render'
.../.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/hanami-view-1.3.1/lib/hanami/view/template.rb:47:in `render'
.../.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/hanami-view-1.3.1/lib/hanami/view/rendering.rb:140:in `rendered'
.../.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/hanami-view-1.3.1/lib/hanami/view/rendering.rb:154:in `layout'
.../.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/hanami-view-1.3.1/lib/hanami/view/rendering.rb:108:in `render'
.../.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/hanami-view-1.3.1/lib/hanami/view/rendering.rb:259:in `render'
.../.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/hanami-1.3.2/lib/hanami/rendering_policy.rb:56:in `_render_action'
.../.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/hanami-1.3.2/lib/hanami/rendering_policy.rb:48:in `_render'
.../.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/hanami-1.3.2/lib/hanami/rendering_policy.rb:38:in `render'
.../.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/hanami-1.3.2/lib/hanami/application.rb:169:in `call'
.../.rbenv/versions/2.4.3/lib/ruby/2.4.0/delegate.rb:83:in `method_missing'
.../.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/http_router-0.11.2/lib/http_router.rb:193:in `process_destination_path'
(eval):54:in `call'
.../.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/http_router-0.11.2/lib/http_router.rb:288:in `raw_call'
.../.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/hanami-router-1.3.1/lib/hanami/routing/http_router.rb:160:in `raw_call'
.../.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/http_router-0.11.2/lib/http_router.rb:142:in `call'
.../.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/hanami-router-1.3.1/lib/hanami/router.rb:1019:in `call'
.../.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rack-2.0.7/lib/rack/method_override.rb:22:in `call'
.../.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/hanami-1.3.2/lib/hanami/assets/static.rb:49:in `call'
.../.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rack-2.0.7/lib/rack/content_length.rb:15:in `call'
.../.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rack-2.0.7/lib/rack/common_logger.rb:33:in `call'
.../.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/hanami-1.3.2/lib/hanami/app.rb:44:in `call'
.../.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rack-2.0.7/lib/rack/static.rb:149:in `call'
.../.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/sentry-raven-2.11.2/lib/raven/integrations/rack.rb:51:in `call'
.../.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/shotgun-0.9.2/lib/shotgun/loader.rb:86:in `proceed_as_child'
.../.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/shotgun-0.9.2/lib/shotgun/loader.rb:31:in `call!'
.../.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/shotgun-0.9.2/lib/shotgun/loader.rb:18:in `call'
.../.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/hanami-1.3.2/lib/hanami/assets/static.rb:49:in `call'
.../.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rack-2.0.7/lib/rack/lint.rb:49:in `_call'
.../.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rack-2.0.7/lib/rack/lint.rb:37:in `call'
.../.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rack-2.0.7/lib/rack/show_exceptions.rb:23:in `call'
.../.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/puma-4.2.0/lib/puma/configuration.rb:228:in `call'
.../.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/puma-4.2.0/lib/puma/server.rb:670:in `handle_request'
.../.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/puma-4.2.0/lib/puma/server.rb:473:in `process_client'
.../.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/puma-4.2.0/lib/puma/server.rb:331:in `block in run'
.../.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/puma-4.2.0/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

**Comment by unleashy** [comment] 2019-09-24 19:48
Seems this is caused by tilt 2.0.10 not 1.3.3 itself. rtomayko/tilt@dbb4df9 this commit specifically seems to have changed the execution of templates and this inadvertently broke something with hanami.

**Comment by unleashy** [comment] 2019-09-24 19:49
rtomayko/tilt#347 is onto it aswell

**Comment by judofyr** [comment] 2019-09-24 20:18
The solution is to add `gem "tilt", "2.0.9"` to your Gemfile for now. Not sure if this deserves a yank. Depends on how quickly we can fix it.

This seems to be a separate bug from rtomayko/tilt#347 though.

**Comment by jodosha** [comment] 2019-09-24 20:53
Thank you all folks for having a look at this. Closing this ticket as it seems to be a `tilt` regression.

**Closed by jodosha** 2019-09-24 20:53 UTC
Labels: invalid

**Comment by jodosha** [comment] 2019-09-25 07:59
@inouire @unleashy I'm working on two patches for `hanami-utils` and `hanami-view` to make Hanami compatible with the latest changes. The release date is set for this Friday.

Please try https://github.com/hanami/utils/pull/343 and https://github.com/hanami/view/pull/160 into your application with `tilt` `2.0.10` and tell us if Hanami plays well with Tilt.

You should temporary edit your `Gemfile` and then run `bundle update hanami-utils hanami-view`:

```ruby
gem "hanami-utils", "~> 1.3", git: "https://github.com/hanami/utils.git", branch: "enhancement/basic-object-constants-lookup"
gem "hanami-view", "~> 1.3", git: "https://github.com/hanami/view.git", branch: "fix/rendering-layout-scope-utils-basic-object"
```

**Comment by inouire** [comment] 2019-09-25 08:01
@jodosha Thanks Luca, I'll try this today and give you a feedback.
