### ISSUE TITLE
Fix use of helpers within parts

### ISSUE THREAD

**Issue by bkuhlmann** [hanami/hanami#1355] opened 2023-07-02 13:59 UTC
**Describe the bug**

Hello. :wave: I've run into an issue with using helpers within parts and wanted to detail the cause and temporary workaround.

**To Reproduce**

The problem is with using *any* helper within a part. Here's a simple implementation:

``` ruby
class Demo < Hanami::View::Part
  include Hanami::View::Helpers::TagHelper

  def label = tag.span value.label
end
```

<details>
  <summary>Spec</summary>

The following spec is being provided in case it helps:

``` ruby
require "spec_helper"

RSpec.describe Demo do
  subject(:part) { described_class.new value: commit, rendering: view.new.rendering }

  let :view do
    Class.new Hanami::View do
      config.paths = [Bundler.root.join("lib/demo/templates")]
      config.template = "n/a"
    end
  end

  let(:commit) { Struct.new(:label).new "Hi" }

  describe "#label" do
    it "answers label" do
      expect(part.label).to eq("<span>Hi</span>")
    end
  end
end
```
</details>

The error you'll get when running the above is:

``` 
 NoMethodError: undefined method `inflector' for #<Demo::Views::Context>...
```

**Expected behavior**

I would not expect to see this error as I think helpers are meant to be used within views and parts?

**Workaround**

There is a workaround to this issue and it has to do with overwriting the private `#tag_builder_inflector` method. Here's a modification of the above impelemtation which makes this work:

``` ruby
class Demo < Hanami::View::Part
  include Hanami::View::Helpers::TagHelper

  def label = tag.span value.label

  private

  def tag_builder_inflector = Dry::Inflector.new
end
```

I'm not sure if this breaks other aspects of Hanami but seems to work. The reason this works is because of these tag helper [lines](https://github.com/hanami/view/blob/main/lib/hanami/view/helpers/tag_helper.rb#L198C1-L200) which check for a context but the problem is that you're getting a `Hanami::View::Rendering` object back which has no `#inflector` message.

**Your environment**

- Affects my production application: **YES**
- Ruby version: ruby 3.2.2 (2023-03-30 revision e51014f9c0) +YJIT [arm64-darwin22.4.0]
- OS: macOS 13.4.1 (22F82)
- **Hanami View**: I'm using the latest SHA on the `main` branch.

**Comment by timriley** [comment] 2023-10-15 23:40
And just moved this issue into hanami/hanami, since that's where our view/default helpers integration resides.

**Comment by bkuhlmann** [comment] 2023-10-16 00:43
I wasn't able to make this work but the error is different now:

``` 
NoMethodError: undefined method `dasherize' for nil:NilClass
```

I also don't have to include `include Hanami::View::Helpers::TagHelper` in my part anymore. So the error, above, happens regardless of whether I include the `TagHelper` or not. Only by not using `tag.span` (or any helper) does the spec pass.

**Comment by timriley** [comment] 2023-10-16 02:40
@bkuhlmann Thanks for the extra info here, @bkuhlmann.

So I made a reproduction producing that error in a new hanami app. In a new app, I created `app/views/parts/demo.rb`:

```ruby
# frozen_string_literal: true

module TestParts
  module Views
    module Parts
      class Demo < Hanami::View::Part
        def label = tag.span(value.label)
      end
    end
  end
end
```

And then a test file, `spec/suite/app/views/parts/demo_spec.rb`:

```ruby
require "spec_helper"

RSpec.describe TestParts::Views::Parts::Demo do
  subject(:part) { described_class.new value: commit, rendering: view.new.rendering }

  let(:view) {
    Class.new(Hanami::View) do
      config.paths = [Bundler.root.join("lib/demo/templates")]
      config.template = "n/a"
    end
  }

  let(:commit) { Struct.new(:label).new "Hi" }

  describe "#label" do
    it "answers label" do
      expect(part.label).to eq("<span>Hi</span>")
    end
  end
end
```

This produced the same error:

```
NoMethodError:
  undefined method `dasherize' for nil:NilClass
```

If I drop a `binding.irb` inside the `it` block in the test, you can see where the issue:

```ruby
part._context.class
# => Hanami::View::Context

part._context.inflector
# => nil
```

The inflector is `nil`, so of course we'll get errors trying to use it.

If we look at where that method comes from, we'll see it comes from Hanami's context framework extension:

```ruby
part._context.method(:inflector)
# => #<Method: Hanami::View::Context(Hanami::Extensions::View::Context::ClassExtension::InstanceMethods)#inflector() /Users/tim/Source/hanami/hanami/lib/hanami/extensions/view/context.rb:73>
```

But what's missing here is the code to _set that inflector_ to the inflector from the app/slice. That code only comes from when we use a view _inside an app or slice namespace_. To wit, if I change the view in the test to this:

```ruby
  let(:view) {
    Class.new(TestParts::View) do
            # ^^^^^^^^^^^^^^^ Changed superclass to view class _inside app_
      config.paths = [Bundler.root.join("lib/demo/templates")]
      config.template = "n/a"
    end
  }
```

Then everything works :) Back at that breakpoint:

```ruby
part._context.class
# => TestParts::Views::Context

part._context.inflector
# => #<Dry::Inflector>
```

And the test passes.

So the takeaway here is: if you want automatic app integration, then you need to use view (and related) classes that come from inside app or slice namespaces. “Class can be found inside an app/slice namespace” is basically the crux of our integration strategy as it stands.

If you can confirm you can get to a passing test based on the advice above, I'll go ahead and close this afterwards.

I'll also make sure I reference this ticket to remind us to include this in examples for when we document testing strategies for views 😄

**Comment by bkuhlmann** [comment] 2023-10-16 19:06
Thanks, confirmed. When using the same view as implemented within my slice then helpers in my parts work and can be tested accordingly. The simplified version is:

``` ruby
# Implementation
class Task < Hanami::View::Part
  def assignee = tag.span user.name
end

# Spec
subject(:part) { described_class.new value: task, rendering: Tasks::View.new.rendering }
```

It's a bit of a bummer that you can't use a lightweight/abstract view for this, though.

I've updated my [article](https://alchemists.io/articles/hanami_views#_parts) to clarify this and will update the article again once `helpers` are introduced into parts to avoid name collisions.

You can close this issue.

**Comment by timriley** [comment] 2023-10-16 23:42
> It's a bit of a bummer that you can't use a lightweight/abstract view for this, though.

You can, _if you don't want to exercise any part of the Hanami's app/slice-level extensions to the view system._

If you needed the Hanami app/slice extensions, you could also manually do this if you really wanted, something like (n.b. untested):

```
view_to_use_for_testing = Class.new(Hanami::View) { |klass|
  config.paths = "..."
  config.template = "n/a"

  klass.configure_for_slice(Hanami.app)
}
```

But at that point, I think you're probably better off just using a base view from inside your app itself. It'll be a more authentic test.

Is it a _bummer_, though? I'm not so sure. It's just part of making sure your tests are realistic. Parts are designed to work within a view rendering, so you need to provide an appropriate one.

This discussion does make me wonder if there's an opportunity to do away with this boilerplate entirely for parts that exist within a Hanami app/slice namespace. I might do a quick experiment on that in the next week or two, if I can find the chance.

**Closed by timriley** 2023-10-16 23:42 UTC
Labels: bug

**Comment by bkuhlmann** [comment] 2023-10-17 00:41
I agree that specs should be as realistic as possible but since a part consumes a view (loosely speaking) it seems like a part should be configured with a safe default -- like a _Null Object_ -- which is benign but allows you to initialize your part in the spec and immediately focus on behavior without needing to construct a view until necessary.

As it stands, currently, it's awkward to test a part without knowing how the rendering works. I had to search around the Hanami View specs to understand this because there is nearly no documentation on this.

Anyway, yes, if there is a way to make parts much easier to instantiate for testing purposes, it'll reduce the learning curve and allow people to focus on implementation much faster.
