### ISSUE TITLE
Pre-Compile fails with Less

### ISSUE THREAD

**Issue by ismaild** [hanami/hanami#546] opened 2016-03-14 17:00 UTC
I am getting the following error when doing `hanami assets precompile` You can see the error by cloning: https://github.com/ismaild/hanami_error/ and running the command.

It looks like the files are being compiled in the wrong order.

**Comment by jodosha** [comment] 2016-03-16 12:47
@ismaild Hello and thanks for reporting this problem. I can confirm it.

---

The example project has the following structure:

```shell
➜ tree apps/web/assets/stylesheets
apps/web/assets/stylesheets
├── application.css.less
└── vendor
    └── luna
        ├── import
        │   └── alerts.import.css.less
        └── style.css.less

3 directories, 3 files
```

When `hanami assets precompile` it's run, it tries to process:

  1. `application.css.less`
  2. `vendor/luna/import/alerts.import.css.less` (this raises an error)

The process fails because that file references a variable defined by `style.css.less`. This last one isn't loaded when Less renders `alerts.import.css.less`.

(This isn't about the loading order, as guessed by @ismaild )

---

`Less::Engine` needs to know where to find all the files of a project. That MUST be specified by the `:paths` option, [passed to the constructor](https://github.com/cowboyd/less.rb/blob/8d94cdd06842121550e957c545420a2460934f52/lib/less/parser.rb#L11).

[We do that only for Sass, but **NOT** for Less](https://github.com/hanami/assets/blob/master/lib/hanami/assets/compiler.rb#L175).

But when I patched it locally, by specifying `:paths`, the problem isn't solved yet.

**NOTE: We need to add `:paths` to `Hanami::Assets::Compiler#compile!`**.

---

`less` gem ships with a `lessc` executable. I tried to compile `alerts.import.css.less` it with the following command:

```shell
➜ bundle exec lessc apps/web/assets/stylesheets/vendor/luna/import/alerts.import.css.less --paths=/Users/luca/Desktop/hanami_error/apps/web/assets:/Users/luca/Desktop/hanami_error/apps/web/assets/images:/Users/luca/Desktop/hanami_error/apps/web/assets/javascripts:/Users/luca/Desktop/hanami_error/apps/web/assets/stylesheets:/Users/luca/Desktop/hanami_error/apps/web/assets/stylesheets/vendor:/Users/luca/Desktop/hanami_error/apps/web/assets/stylesheets/vendor/luna:/Users/luca/Desktop/hanami_error/apps/web/assets/stylesheets/vendor/luna/import
at /Users/luca/.gem/ruby/2.3.0/gems/less-2.6.0/lib/less/js/lib/less/parser.js:604:31: variable @color-accent is undefined (Less::ParseError)
	from /Users/luca/.gem/ruby/2.3.0/gems/less-2.6.0/lib/less/parser.rb:100:in `block in to_css'
	from /Users/luca/.gem/ruby/2.3.0/gems/less-2.6.0/lib/less/java_script/v8_context.rb:90:in `block in do_lock'
	from /Users/luca/.gem/ruby/2.3.0/gems/less-2.6.0/lib/less/java_script/v8_context.rb:88:in `Locker'
	from /Users/luca/.gem/ruby/2.3.0/gems/less-2.6.0/lib/less/java_script/v8_context.rb:88:in `do_lock'
	from /Users/luca/.gem/ruby/2.3.0/gems/less-2.6.0/lib/less/java_script/v8_context.rb:60:in `lock'
	from /Users/luca/.gem/ruby/2.3.0/gems/less-2.6.0/lib/less/java_script/v8_context.rb:30:in `exec'
	from /Users/luca/.gem/ruby/2.3.0/gems/less-2.6.0/lib/less/java_script.rb:26:in `exec'
	from /Users/luca/.gem/ruby/2.3.0/gems/less-2.6.0/lib/less/parser.rb:100:in `to_css'
	from /Users/luca/.gem/ruby/2.3.0/gems/less-2.6.0/bin/lessc:101:in `<top (required)>'
	from /Users/luca/.gem/ruby/2.3.0/bin/lessc:23:in `load'
	from /Users/luca/.gem/ruby/2.3.0/bin/lessc:23:in `<main>'
```

This seems to be a problem with `Less::Parser`.
@ismaild Can you please try the same steps and confirm my hypothesis? Thanks!

**Comment by ismaild** [comment] 2016-03-17 20:56
@jodosha i am getting the same error as well.

**Comment by jodosha** [comment] 2016-03-18 08:28
@ismaild Thanks for checking. Let's involve Less maintainers. :smile:

**Comment by jodosha** [comment] 2016-03-26 07:53
Note: I've added the `:paths` option to `hanami-assets` compilation process for Less: https://github.com/hanami/assets/commit/83435835d43e024319add216462b7f57a7d601d5

---

We can close this ticket and eventually open it again when Less maintainers will reply.

**Closed by jodosha** 2016-03-26 07:53 UTC
Labels: bug
