### ISSUE TITLE
Unable to create example project

### ISSUE THREAD

**Issue by kevinrobayna** [hanami/hanami#1274] opened 2022-12-30 17:34 UTC
I was following the getting started guide buy I'm unable to create the example bookshelf

I had ruby installed with rbenv but I gave a try to reinstall ruby with asdf to see if that would fix the issue.

https://guides.hanamirb.org/v2.0/introduction/getting-started/

This is what I tried after reinstalling ruby.

```
for x in `gem list --no-versions` ; do gem uninstall $x -a -x -I ; done # To clean up all the dependencies
bundle install # To install default dependencies
gem install hanami
gem install hanami-cli # to make sure is there
```

Error:
```
❯  hanami new bookshelf
/Users/krobayna/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/hanami-cli-2.0.2/exe/hanami:5:in `require': cannot load such file -- hanami/cli (LoadError)
	from /Users/krobayna/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/hanami-cli-2.0.2/exe/hanami:5:in `<top (required)>'
	from /Users/krobayna/.asdf/installs/ruby/3.2.0/bin/hanami:25:in `load'
	from /Users/krobayna/.asdf/installs/ruby/3.2.0/bin/hanami:25:in `<main>'
```

System 
```
❯ ruby --version
ruby 3.2.0 (2022-12-25 revision a528908271) [arm64-darwin22]
❯ which ruby
/Users/krobayna/.asdf/shims/ruby
❯ which hanami
/Users/krobayna/.asdf/shims/hanami
❯ hanami --version
/Users/krobayna/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/hanami-cli-2.0.2/exe/hanami:5:in `require': cannot load such file -- hanami/cli (LoadError)
	from /Users/krobayna/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/hanami-cli-2.0.2/exe/hanami:5:in `<top (required)>'
	from /Users/krobayna/.asdf/installs/ruby/3.2.0/bin/hanami:25:in `load'
	from /Users/krobayna/.asdf/installs/ruby/3.2.0/bin/hanami:25:in `<main>'
❯ hanami
/Users/krobayna/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/hanami-cli-2.0.2/exe/hanami:5:in `require': cannot load such file -- hanami/cli (LoadError)
	from /Users/krobayna/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/hanami-cli-2.0.2/exe/hanami:5:in `<top (required)>'
	from /Users/krobayna/.asdf/installs/ruby/3.2.0/bin/hanami:25:in `load'
	from /Users/krobayna/.asdf/installs/ruby/3.2.0/bin/hanami:25:in `<main>'
```

Also just for context I can install other gems (like rails) and run them just fine.

**Comment by kevinrobayna** [comment] 2022-12-31 16:59
It has to be something related to my installation because when I do this, it just works :/

```
docker run --rm --name hanami -it ruby:3.2-alpine ash
/ # gem install hanami
/ # which ruby
/usr/local/bin/ruby
/ # gem install ^Cnami
/ # hanami new bookshelf
Created bookshelf/
-> Within bookshelf/
Created .env
Created README.md
Created Gemfile
Created Rakefile
Created config.ru
Created config/app.rb
Created config/settings.rb
Created config/routes.rb
Created config/puma.rb
Created lib/tasks/.keep
Created lib/bookshelf/types.rb
Created app/actions/.keep
Created app/action.rb
Running Bundler install...
```

**Comment by solnic** [comment] 2023-01-01 16:19
Yes this most likely has something to do with your local setup. Try purging your installation and installing things again. This typically helps. I'm gonna close this because I'm 99.999999999% sure it's not a bug on our side. Please feel free to re-open and provide more information in case I was wrong.

**Closed by solnic** 2023-01-01 16:19 UTC

**Comment by parndt** [comment] 2023-03-26 22:38
I had this happen and the reason why is that the directory I was generating into had a `Gemfile` already.

**Comment by kevinrobayna** [comment] 2023-04-12 17:16
> I had this happen and the reason why is that the directory I was generating into had a `Gemfile` already.

same reason for me!! I didn't have it in the same folder but I had a gemfile on `~` removing it solved my issue!
