### ISSUE TITLE
Allow host to be set when mounting apps in the container

### ISSUE THREAD

**Issue by sandelius** [hanami/hanami#656] opened 2016-10-19 06:40 UTC
It would be really nice to set a host (String, Regexp) in the container like this:

``` ruby
Hanami::Container.configure do
  mount Api::Application, at: '/', host: /\Aapi\.*/
  mount Auth::Application, at: '/auth'
end
```

**Comment by jodosha** [comment] 2016-10-24 07:09
@hanami/core-team @hanami/contributors WDYT?

**Comment by AlfonsoUceda** [comment] 2016-10-24 07:12
@sandelius could you provide an example? I mean, what do you want to do with that option? I can imagine urls will be generated to that endpoint, but if you can explain a little more.
Thanks!

**Comment by sandelius** [comment] 2016-10-24 07:25
Let's say I have two apps, one called web and one called api. I want bort to be served from `/` but the API will only be served from the `api.` subdomain.

```ruby
Hanami::Container.configure do
  mount Api::Application, at: '/', host: /\Aapi\.*/
  mount Web::Application, at: '/'
end
```

ping @jodosha @AlfonsoUceda

**Comment by mereghost** [comment] 2016-10-25 16:34
@sandelius A rewrite rule (on the http server) wouldn't suffice for that?

**Comment by sandelius** [comment] 2016-10-26 18:07
@mereghost yeah we can do it there but not everyone have access to it easily. I can do it like that but I think it's a feature that should be in Hanami.

Also it would make it a bit easier during development.

**Comment by TiteiKo** [comment] 2016-10-26 18:26
As far as I've tried, rewrite rules don't necessarily do well with non-GET http methods, so that might be a problem for an api

IMHO, it's a feature that should be in Hanami, as it is in line with the container architecture and it's common to have/need subdomains like `admin.example.com, dashboard.example.com, api.example.com, ...` or even an entirely other domain.

**Comment by mereghost** [comment] 2016-10-26 18:38
@sandelius I see. The thing is that a server will need to be setup hear to that subdomain and whatnot, so a bit of Ops work goes there so it would be simpler to leave routing subdomains (and internal rewrites) to the proven tech that already does it. =) Besides it's less code to maintain.

 That being said, if implementing that would be a breeze, I'm all for it. 👍 

@TiteiKo I'm not sure that I follow you on the whole *in line with the container arch* tho 😞 Could you elaborate a bit (can be over gitter so we do not pollute here with a tangent discussion).

**Comment by pascalbetz** [comment] 2016-10-26 18:41
@mereghost 

Hanami Supports the "Container Architecture". You can think of it as multiple, separated apps inside one Application.

**Comment by mereghost** [comment] 2016-10-26 19:12
@pascalbetz Yep. I know that, i just fail to see how that relates to supporting multiple (sub)domains.

**Comment by pascalbetz** [comment] 2016-10-26 19:15
@mereghost almost expected:-)

You could imagine mounting apps on subdomains instead of paths.

**Comment by joneslee85** [comment] 2016-10-26 20:46
It is indeed an interesting usecase. I myself question if it should be in hanami as it adds much more complexity. This usecase could be solved with external devops stack instead by running apps on different instances. 

FYI, I find it is similar to Rails routing constraint http://guides.rubyonrails.org/routing.html#request-based-constraints

**Comment by cllns** [comment] 2016-11-02 17:07
It looks like this might already be partially supported? For a string (not a regex) specifying the entire host (not just the subdomain): https://github.com/hanami/router/pull/104

Also, this is a duplicate of https://github.com/hanami/router/issues/48

**Comment by AlfonsoUceda** [comment] 2017-01-28 22:33
@sandelius is it ok for you using a string? You can use it, see the previous comment.

**Comment by sandelius** [comment] 2017-02-09 07:03
@AlfonsoUceda if we could use a regex it would make it a whole lot simpler to match both dev and production environments.

**Closed** 2018-03-22 14:08 UTC
Labels: discussion, for-future-consideration
