### ISSUE TITLE
Provider lifecycle execution is unclear

### ISSUE THREAD

**Issue by sphinxc0re** [hanami/hanami#1296] opened 2023-03-02 15:03 UTC
Just tested this with a fresh hanami setup (hanami new) and an extremely plain debugging provider (just for logging). After starting the app I got the following output:

```
[182090] Puma starting in cluster mode...
[182090] * Puma version: 6.1.1 (ruby 3.2.1-p31) ("The Way Up")
[182090] *  Min threads: 5
[182090] *  Max threads: 5
[182090] *  Environment: development
[182090] *   Master PID: 182090
[182090] *      Workers: 2
[182090] *     Restarts: (✔) hot (✖) phased
[182090] * Preloading application
[testibus] [DEBUG] [2023-02-28 20:53:47 +0100] DEBUGGY BOY! PREPARE!
[testibus] [DEBUG] [2023-02-28 20:53:47 +0100] DEBUGGY BOY! START!
[182090] * Listening on http://0.0.0.0:2300
[182090] Use Ctrl-C to stop
[182090] * Starting control server on http://127.0.0.1:9293
[182090] * Starting control server on http://[::1]:9293
[testibus] [DEBUG] [2023-02-28 20:53:47 +0100] DEBUGGY BOY! STOP!
[182090] - Worker 0 (PID: 182096) booted in 0.0s, phase: 0
[testibus] [DEBUG] [2023-02-28 20:53:47 +0100] DEBUGGY BOY! STOP!
[182090] - Worker 1 (PID: 182098) booted in 0.0s, phase: 0
```
This doesn't make a ton of sense to me. Why is the `stop` hook called **twice** during the startup of the app?

**Comment by solnic** [comment] 2023-03-02 16:59
Because you have two workers by default

**Comment by sphinxc0re** [comment] 2023-03-02 17:05
Okay but that neither explains why `stop` is called on startup nor why the `prepare` and `start` are only called once. I just don't get why `stop` is called on startup at all. Shouldn't it only be called when the app shuts down?

**Comment by solnic** [comment] 2023-03-02 21:01
Huh right, I didn't notice that it's `stop`. This does look weird. Hard to tell what's going on without debugging it first.

**Comment by timriley** [comment] 2023-03-02 23:28
Hi @sphinxc0re, thanks for bringing this up!

Seeing a "stop" during boot here is by design, because you're doing your testing via Puma, which is a pre-forking web server.

When you generate a new Hanami app, you'll see this line in your `config/puma.rb`:

```ruby
on_worker_boot do
  Hanami.shutdown
end
```

What `Hanami.shutdown` will do is call `#stop` on all providers.

The reason this is here is to make sure any active connections to external resources are reestablished as part of Puma's individual worker booting, basically [following the advice from this document from Heroku's devcenter](https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server#on-worker-boot).

However, now that I'm seeing it again, I think things are not quite right:

1. Firstly, we should ideally only be calling `stop` once, _before_ the Puma workers boot
2. And maybe we don't need it at all, given [this issue](https://github.com/rails/rails/pull/31241) linked from the devcenter page. If we can confirm that most of our tools are "fork-proof" too, then it might be a better default posture _not_ to force everything to stop, and instead let users explicitly opt into this behaviour if they have any custom providers that need this.

I think we could look into (1) as soon as is practical, since we could argue it's a bug with the current setup. And we should definitely look into (2) as part of integrating our persistence layer, since it's the connection to the database that's most relevant to this part of the app lifecycle.

**Comment by timriley** [comment] 2023-03-03 00:01
BTW, just to show that this is Puma-specific, if you instead started `hanami console` and typed `boot`, you'd see that none of the "stop" lifecycle events were triggered. This is because we don't call `Hanami.shutdown` anywhere _except_ via that `config/puma.rb`.

**Comment by sphinxc0re** [comment] 2024-02-27 14:27
This issue seems to be fixed. What do you folks think?

```
 Puma starting in single mode...
 * Puma version: 6.4.2 (ruby 3.3.0-p0) ("The Eagle of Durango")
 *  Min threads: 5
 *  Max threads: 5
 *  Environment: development
 *          PID: 78205
 [video_cave] [INFO] [2024-02-27 15:25:20 +0100] PREPARE!
 [video_cave] [INFO] [2024-02-27 15:25:20 +0100] START!
 * Listening on http://0.0.0.0:2300
 * Starting control server on http://127.0.0.1:9293
 * Starting control server on http://[::1]:9293
 Use Ctrl-C to stop
```

**Comment by timriley** [comment] 2024-03-04 13:05
@sphinxc0re Thanks for following this up, and yes, you're right! This was fixed by https://github.com/hanami/cli/pull/108, where we switched from using `on_worker_boot` to `before_fork`.

It was also addressed by https://github.com/hanami/cli/pull/86, where we defaulted not to use workers in the first place.

**Closed by timriley** 2024-03-04 13:05 UTC
