### ISSUE TITLE
Memory issues after upgrade?

### ISSUE THREAD

**Issue by atog** [hanami/hanami#1073] opened 2020-09-02 19:26 UTC
Yesterday evening I upgraded my Hanami application from version 1.1.1 to version 1.3.3 (Ruby 2.5.1). It's running on Heroku. When my users started working today I noticed a strong increase in memory usage, until the application was down. I restarted to app two times to no avail.

In the end I reverted the specific commit containing the upgrade, deployed, and the app was running smooth again. I haven't been able to investigate further, it could be the due the `rack-ssl-enforcer` gem which was not present before the upgrade either.

<img width="1199" alt="Screenshot 2020-09-02 at 21 13 07" src="https://user-images.githubusercontent.com/5460/92027332-a9d35a00-ed62-11ea-9fb8-2cdfb4477782.png">

Anyways, I wanted to write it down somewhere in case I'm missing something obvious.

**Comment by adam12** [comment] 2021-02-16 11:58
Hi @atog 

Has there been any update to this? Are you still on 1.1.1?

**Comment by atog** [comment] 2021-02-16 12:56
Yep, I did not try to upgrade again since.

**Comment by adam12** [comment] 2021-02-16 13:26
Are you able to provide a diff of the `Gemfile.lock` from the upgrade? It would be great to see everything that changed.

I looked at the `rack-ssl-enforcer` gem and it's more complex than I expected.

**Comment by atog** [comment] 2021-02-17 08:33
@adam12 here you go!

![gemlock-diff](https://user-images.githubusercontent.com/5460/108177180-2dabb380-7103-11eb-9160-fb05028706d8.png)

**Comment by adam12** [comment] 2021-02-28 20:06
Closing for now since I don't think it's related to Hanami with current data.

I attempted to reproduce this by dual-booting `bookshelf` for both 1.1 and 1.3, but memory usage for both was near identical (I ran 50 curls and then checked PSS using `process-metrics`).

## To reproduce

1. Add `puma` and `process-metrics` to Gemfile.
2. Run `puma config.ru` and then `process-metrics --pid <pid>`
3. Curl `http://localhost:9292` a few times, then `process-metrics --pid <pid>`

Repeat for both versions of Hanami.

## Results

1.1 after 50 requests: 65.9 MiB
1.3 after 50 requests: 65.7 MiB

**Closed by adam12** 2021-02-28 20:06 UTC
Labels: performance, question, waiting
