### ISSUE TITLE
Remove quotes in .env.development and .env.test

### ISSUE THREAD

**Issue by apohllo** [hanami/hanami#897] opened 2018-02-13 18:10 UTC
I'm wondering if it would be possible to remove quotes in the `.env` files. I use docker together with Hanami, which I think is quite common at present. Docker compose has an option to take the env. variables from a file, and `.env` files seem to be good place to store these variables. But - there is one important difference - Docker treats the quotes as regular characters! 
I don't know what is the reason for that, since bash works differently, but I guess it will be easier to change Hanami than Docker :-]
Would you consider such a change?

**Comment by kaikuchn** [comment] 2018-02-14 08:15
Hey apohllo,

thanks for raising this issue. I wasn't aware of the friction those quotes may cause. In fact, the dotenv gem (which is used for loading those dot-files) does not care whether your values have quotes around them or not. I.e., you can just drop them an everything **should** still be working.

I can't think of anything that would prevent Hanami from changing the default generated `.env.development` and `.env.test` files.

**Comment by apohllo** [comment] 2018-02-14 08:57
Thanks!

**Comment by AlfonsoUceda** [comment] 2018-02-17 17:37
Hi @apohllo

We generate just two environment variables `DATABASE_URL` and `SERVE_STATIC_ASSETS`, I suppose we can remove quotes for `SERVE_STATIC_ASSETS` but I'm not 100% sure for `DATABASE_URL`. IMO you can fix it just editing this file, in addition you'll add more environment variables when working in your app.

For now, I'm going to close the issue but if in the future there are more complaints, we can think about this. Thanks anyway.

**Closed by AlfonsoUceda** 2018-02-17 17:37 UTC

**Comment by apohllo** [comment] 2018-04-04 13:40
@AlfonsoUceda I agree, these are only two variables, but maybe we could put some comment in the generated file informing, that using that file as an input for Docker is a bad idea?
The problem is that I spend several hours trying to figure out the what's going on. I thought there was a problem with my DB configuration, with credentials, with passinge the variablest to Docker, etc. So a word of warning would be a good idea.

@jodosha Ok, I'll create the repo.

**Comment by apohllo** [comment] 2018-04-26 18:17
I've created the repo 
https://github.com/apohllo/quotes

The instruction to reproduce the problem is given in the Readme file.

**Comment by jodosha** [comment] 2018-05-08 15:59
@apohllo Thanks for your demo app. I can reproduce all the steps you wrote in README.

This seems to be a problem of Docker Compose, https://github.com/docker/compose/issues/3702. IMO it should work both with quoted and unquoted vars.
