### ISSUE TITLE
uninitialized constant BetterErrors::Middleware::VERSION

### ISSUE THREAD

**Issue by johnpitchko** [hanami/hanami#1080] opened 2020-10-02 02:27 UTC
Launching my first Hanami app by following the **Getting Started** guide at https://guides.hanamirb.org/introduction/getting-started/.

Ran the following:
```
$ gem install hanami
$ hanami new bookshelf
$ cd bookshelf
$ bundle install
$ bundle exec hanami server
uninitialized constant BetterErrors::Middleware::VERSION
/usr/local/lib/ruby/gems/2.7.0/gems/better_errors-2.8.2/lib/better_errors/middleware.rb:43:in `<class:Middleware>'
	/usr/local/lib/ruby/gems/2.7.0/gems/better_errors-2.8.2/lib/better_errors/middleware.rb:28:in `<module:BetterErrors>'
	/usr/local/lib/ruby/gems/2.7.0/gems/better_errors-2.8.2/lib/better_errors/middleware.rb:7:in `<top (required)>'
	/usr/local/lib/ruby/gems/2.7.0/gems/better_errors-2.8.2/lib/better_errors.rb:9:in `require'
	/usr/local/lib/ruby/gems/2.7.0/gems/better_errors-2.8.2/lib/better_errors.rb:9:in `<top (required)>'
	/usr/local/lib/ruby/gems/2.7.0/gems/hanami-webconsole-0.1.0/lib/hanami/webconsole/plugin.rb:3:in `require'
	/usr/local/lib/ruby/gems/2.7.0/gems/hanami-webconsole-0.1.0/lib/hanami/webconsole/plugin.rb:3:in `<top (required)>'
	/usr/local/lib/ruby/gems/2.7.0/gems/hanami-webconsole-0.1.0/lib/hanami/webconsole.rb:9:in `require'
	/usr/local/lib/ruby/gems/2.7.0/gems/hanami-webconsole-0.1.0/lib/hanami/webconsole.rb:9:in `<module:Webconsole>'
	/usr/local/lib/ruby/gems/2.7.0/gems/hanami-webconsole-0.1.0/lib/hanami/webconsole.rb:7:in `<module:Hanami>'
	/usr/local/lib/ruby/gems/2.7.0/gems/hanami-webconsole-0.1.0/lib/hanami/webconsole.rb:3:in `<top (required)>'
	/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:88:in `require'
	/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:88:in `rescue in block in require'
	/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:65:in `block in require'
	/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `each'
	/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `require'
	/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler.rb:174:in `require'
	/usr/local/lib/ruby/gems/2.7.0/gems/hanami-1.3.3/lib/hanami/setup.rb:3:in `<top (required)>'
```

[Gemfile gist](https://gist.github.com/johnpitchko/9ccbc546082d5805de9ca14550767afb)

**Comment by johnpitchko** [comment] 2020-10-02 02:45
Seems like a [bug](https://github.com/BetterErrors/better_errors/issues/479) in v2.8.2 of better_errors. Tried to downgrade to v2.8.1 but Hanami is telling me that 2.8.2 is required. Anyway I can run Hanami with v2.8.1 of better_errors?

**Comment by cllns** [comment] 2020-10-02 03:19
Sorry you ran into this proble. Thanks for looking into the cause too/ I was just able to reproduce it

If you add `gem "better_errors", "2.8.1"` to the Gemfile, then run `bundle update better_errors`, it should downgrade to the right version. Voila!

Hanami only requires `better_errors` 2.4 or higher right now, so it's not a Hanami issue. Going to close this because I'm quite sure the above instruction will solve this, but feel free to continue commenting and we can re-open if that doesn't fix it.

Hopefully they'll release a `2.8.3` of `better_errors` soon and this won't bite anyone else 🌸

**Closed by cllns** 2020-10-02 03:19 UTC

**Comment by johnpitchko** [comment] 2020-10-02 14:09
Yes I was able to change the version of Better_Errors in the Gemfile.lock to 2.8.1 re-fresh the gems via bundler and that seemed to work (a hack I know, but I don't really know what I'm doing).

I'll try your idea.
