### ISSUE TITLE
static files failed to serve automatically with multiple apps

### ISSUE THREAD

**Issue by sibojia** [hanami/hanami#640] opened 2016-08-19 09:18 UTC
There is a potential issue about `Static asset serving`. It's suspect that the container failed to load static files correctly for multiple apps if the mount path is not default.

The demo project and the steps to reproduce can be found in
https://github.com/sibojia/static_path_test

Thanks!

**Comment by bruz** [comment] 2016-08-23 05:47
Thanks for the example app demonstrating the issue, that's always a big help.

I can confirm `test.js` from the `web` app serving from the `another` app at [http://localhost:2300/home](http://localhost:2300/home) if there isn't a separate mount point specified for the `web` app. That doesn't seem ideal but is there a case where the two apps wouldn't be mounted at different paths in practice? I'm curious what the use case is where you're hitting this issue.

**Comment by sibojia** [comment] 2016-08-24 03:55
Thanks @bruz for your help! I'm new to hanami and encountered this problem when I'm following the get-start guide. I'm sticking with the 'another' app and don't want to mount the default 'web' app. Actually I think use cases exist when containers are deployed on different servers and some need to mount only one of the apps (e.g. client app) ?

**Comment by bruz** [comment] 2016-08-25 07:39
That's an interesting use case, I was thinking in order to serve an app separately it would be broken out as a separate codebase. But, even with what you're proposing, it looks like commenting out `require_relative '../apps/web/application'` app in `environment.rb` gets it to not serve assets from the `web` app, which is at least a workaround.

In terms of not serving assets if the app isn't mounted, which makes sense to me, the issue appears to be that once the app is required, `hanami-assets` will default to serve the assets under `/assets`. I'm wondering if it'd be better to follow the way `hanami-router` works and by one means or another not serve assets at all in the case where the application hasn't been mounted.

**Comment by mereghost** [comment] 2017-02-06 16:41
Tested against `hanami-master` and everything worked out nicely. Was fixed by #704 .

**Closed by mereghost** 2017-02-06 16:41 UTC
Labels: bug
