### ISSUE TITLE
Error pages for JSON/slim application

### ISSUE THREAD

**Issue by apohllo** [hanami/hanami#889] opened 2018-01-16 16:41 UTC
I have an application that is configured to serve JSON. Moreover the templating engine is set to slim.
However when I try to substitute the default error pages (e.g. for 404) the file `app/web/templates/404.json.slim` is not used. I provided `app/web/templates/404.html.erb` and it turned out that this file is served in that context. Is it by design or is it a bug?

**Comment by cllns** [comment] 2018-01-17 01:28
Sorry you had trouble @apohllo.

I just tried using a `slim` html template and it worked fine. So the issue is the JSON part. (Also, `slim` is used to generate HTML/XML, not JSON.)

Similarly, we _could_ add support for `404.json.erb`, but generating JSON via ERB is also not recommended since it's easy to mess up. Instead, a good approach for generating is to use `Hash#to_json`.

I think you can handle this at the Rack level, rather than the Hanami level.

For example, you could make your `config.ru` file something like this:

```ruby
require './config/environment'

class UseJSONFor404s
  def initialize(app)
    @app = app
  end

  def call(env)
    @app.call(env).tap do |response|
      if response[0] == 404 # && env['HTTP_ACCEPT'] == 'application/json'
        return [
          404,
          { "Content-Type" => "application/json" },
          [ { status: 404, error: "oh noooo it cannot be found!" }.to_json ]
        ]
      end
    end
  end
end

use UseJSONFor404s
run Hanami.app
```

This will turn all 404's into JSON responses. If you have any HTML in the app, you probably want to check to make sure that only JSON requests are responded to with JSON. To do that, un-comment the second part of the conditional above.

You can test it out on the command line with this
```shell
$ curl -X GET -H 'Accept: application/json' -i http://localhost:2300
HTTP/1.1 404 Not Found
Content-Type: application/json
Server: WEBrick/1.3.1 (Ruby/2.4.1/2017-03-22)
Date: Wed, 17 Jan 2018 01:18:42 GMT
Content-Length: 53
Connection: Keep-Alive

{"status":404,"error":"oh noooo it cannot be found!"}%
```

```shell
$ curl -X GET -H 'Accept: application/html' -i http://localhost:2300
HTTP/1.1 404 Not Found
Content-Type: application/octet-stream
Content-Length: 1386
Server: WEBrick/1.3.1 (Ruby/2.4.1/2017-03-22)
Date: Wed, 17 Jan 2018 01:19:41 GMT
Connection: Keep-Alive

<!DOCTYPE html>
<html>
  # ...
  # <head> removed for brevity
  # ...
  <body>
    <div id="container">
      <h2>404 - Not Found</h2>
    </div>
  </body>
</html>
```

Others feel free to chime in with other possible solutions, but I'm going to close this for now. I've added the `wontfix` label to this, since it can be handled outside of Hanami.

Note: I think sensible JSON error pages could and should be built into Hanami. A default response of something like `{"status": 404, "text": "Not Found"}`, but we don't want to assume too much about what users' responses would look like. Maybe that could be a part of a `hanami-api` gem #885 @Serhiy-Nazarov? If we want to discuss adding that to Hanami proper, it should be its own Issue.

Thanks! 🌸

**Closed by cllns** 2018-01-17 01:28 UTC
Labels: wontfix

**Comment by apohllo** [comment] 2018-01-17 11:35
Thanks!
To clarify - I know that generating JSON responses by slim/erb is not the best idea ;-) But I wanted just to serve a static 404 content - instead of the one that is by default provided by Hanami. I thought that since the application is configured to serve JSON, I should provide a JSON template, rather than an HTML template. This is the case in the context of views, thus at present it seems that the naming scheme is inconsistent with respect to the response type in case of the errors.

Regarding the built-in response: I think that as long as the user can easily substitute the template (like in the case of "HTML" response) it's fine to serve anything that parses as a JSON string as an answer for a JSON request.
